const cattleModule = {
    index: {
        Cow: 'Mi ganado',
        Cattle: 'Mis lotes',
        Sale: 'Vender',
        Buy: 'Comprar',
        Death: 'Dar de baja',
        CowLote: 'Bovinos del lote',
        CowFarm: 'Bovinos en la finca',
        MoveCattle: 'Mover ganado'
    },

    form: {
        Id: 'Identificación',
        IdCow: 'Identificación del bovino',
        EditCow: 'Editar bovino',
        IdCattle: 'Identificación del lote',
        CowType: 'Estado del bovino',
        NewLote: 'Crear lote',
        MoveCattle: 'Trasladar ganado',
        CattleNewLote: 'Bovinos a ingresar en el nuevo lote',
        IdNewLote: 'Identificación del nuevo lote',
        InfoNewLote: 'Información del nuevo lote',
        TypeNewLote: 'Tipo de lote',
        InfoLote: 'Información del lote',
        TypeLoteOptions: [
            { key:'Cría hembra: CH' , value: 'Cría hembra: CH' },
            { key: 'Cría macho: CM', value: 'Cría macho: CM' },
            { key: 'Hembra de ceba: HC', value: 'Hembra de ceba: HC' },
            { key: 'Hembra levante: HL' , value: 'Hembra levante: HL' },
            { key: 'Macho de ceba: MC', value: 'Macho de ceba: MC' },
            { key: 'Macho levante: ML', value: 'Macho levante: ML' },
            { key: 'Novilla vientre: NV', value: 'Novilla vientre: NV' },
            { key: 'Toros: TR', value: 'Toros: TR' },
            { key: 'Vaca horra: VH', value: 'Vaca horra: VH' },
            { key: 'Vaca parida: VP', value: 'Vaca parida: VP' },
            { key: 'Mixto', value: 'Mixto' },
        ],
        CowTypeOpt: [
            { key: '1', value: 'Leche' },
            { key: '2', value: 'Carne' },
            { key: '3', value: 'Doble propósito' }

        ],
        SexCow: 'Sexo del bovino',
        SexCattle: 'Sexo del lote',
        Race: 'Raza',
        RaceCattle: 'Raza del lote',
        NameCow: 'Nombre',
        ActionLote: 'Tareas del lote',
        MoveCow: 'Trasladar',
        AmountCattle: 'Cantidad de bovinos',
        PriceCow: 'Precio del bovino',
        PriceCattle: 'Precio del lote',
        PriceSaleCow: 'Valor',
        WeightCow: 'Peso del bovino',
        WeightCowSale: 'Peso ',
        WeigthCattle: 'Peso del lote',
        Female: 'Hembra',
        Male: 'Macho',
        Mix: 'Mixto',
        Photo: 'Registre una fotografia del bovino',
        CattlePhoto: 'Registre una fotografia del lote',
        HeadTable: ['Id', 'Nombre', 'Sexo', 'Peso', 'Ingreso'],
        LoteName: 'Nombre del lote',
        LoteClass: 'Clase de lote',
        CowCant: 'Cantidad de bovinos',
        searchHelp: "Busca tu bovino",
        BuyHelp: 'Desea registrar la compra de',
        SaleHelp: 'Desea registrar la venta de',
        InfoSale: 'Información de la venta',
        InfoDeath: 'Información de la muerte',
        Type: ['Lote', 'Bovino'],
        RegisterBuy: 'Registrar la compra',
        RegisterSale: 'Registrar venta',
        RegisterDeath: 'Registrar muerte',
        WarningSale: '¿Desea registrar la venta?',
        Warningdeath: '¿Desea registrar la muerte del bovino?',
        ReceOptions: [
            { key: 'Aberdeen Angus', value: 'Aberdeen Angus' },
            { key: 'Angus', value: 'Angus' },
            { key: 'Ayrshire', value: 'Ayrshire' },
            { key: 'Balancer', value: 'Balancer' },
            { key: 'Beefbuilder', value: 'Beefbuilder' },
            { key: 'Beefmaster', value: 'Beefmaster' },
            { key: 'Belted Galloway', value: 'Belted Galloway' },
            { key: 'Black Baldy', value: 'Black Baldy' },
            { key: 'Blonde d\'Aquitaine', value: 'Blonde d\'Aquitaine' },
            { key: 'Blanco Orejinegro', value: 'Blanco Orejinegro' },
            { key: 'Brangus', value: 'Brangus' },
            { key: 'Brahmousin', value: 'Brahmousin' },
            { key: 'Brahman', value: 'Brahman' },
            { key: 'Brown Swiss', value: 'Brown Swiss' },
            { key: 'Casanareño', value: 'Casanareño' },
            { key: 'Charolais', value: 'Charolais' },
            { key: 'Charolais Composite', value: 'Charolais Composite' },
            { key: 'Chianina', value: 'Chianina' },
            { key: 'Chino Santandereano', value: 'Chino Santandereano' },
            { key: 'Cebú Costeño', value: 'Cebú Costeño' },
            { key: 'Costeño con Cuernos', value: 'Costeño con Cuernos' },
            { key: 'Friesian', value: 'Friesian' },
            { key: 'Gelbvieh', value: 'Gelbvieh' },
            { key: 'Guernsey', value: 'Guernsey' },
            { key: 'Gyr', value: 'Gyr' },
            { key: 'Gyr-Jersey', value: 'Gyr-Jesrsey' },
            { key: 'Gyrolanda', value: 'Gyrolanda' },
            { key: 'Hartón del Valle', value: 'Hartón del Valle' },
            { key: 'Hereford', value: 'Hereford' },
            { key: 'Highland', value: 'Highland' },
            { key: 'Holstein', value: 'Holstein' },
            { key: 'Holstein-Simmental', value: 'Holstein-Simmental' },
            { key: 'Jerhol', value: 'Jerhol' },
            { key: 'Jersey', value: 'Jersey' },
            { key: 'Lim-Flex', value: 'Lim-Flex' },
            { key: 'Limousin', value: 'Limousin' },
            { key: 'Limousin Composite', value: 'Limousin Composite' },
            { key: 'Marchigiana', value: 'Marchigiana' },
            { key: 'Milking Shorthorn', value: 'Milking Shorthorn' },
            { key: 'Montbeliarde', value: 'Montbeliarde' },
            { key: 'Murray Grey', value: 'Murray Grey' },
            { key: 'Nelore', value: 'Nelore' },
            { key: 'Normando', value: 'Normando' },
            { key: 'Pardo Suizo', value: 'Pardo Suizo' },
            { key: 'Piedmontese', value: 'Piedmontese' },
            { key: 'Red Angus', value: 'Red Angus' },
            { key: 'Red Brangus', value: 'Red Brangus' },
            { key: 'Romosinuano', value: 'Romosinuano' },
            { key: 'Salers', value: 'Salers' },
            { key: 'Sanmartinero', value: 'Sanmartinero' },
            { key: 'Santa Cruz', value: 'Santa Cruz' },
            { key: 'Santa Gertrudis', value: 'Santa Gertrudis' },
            { key: 'Shorthorn', value: 'Shorthorn' },
            { key: 'Sinuano', value: 'Sinuano' },
            { key: 'SimAngus', value: 'SimAngus' },
            { key: 'Simmental', value: 'Simmental' },
            { key: 'Texas Longhorn', value: 'Texas Longhorn' },
            { key: 'Tigerstripe', value: 'Tigerstripe' },
            { key: 'Velásquez', value: 'Velásquez' },
            { key: 'Veloceño', value: 'Veloceño' },
            { key: 'Wagyu', value: 'Wagyu' },
            {key:'Otra', value:'Otra'}
           
        ],
        MoveMessage: 'Animales que desea trasladar',
        MoveMessageButtom: ['Esta apunto de trasladar', 'bovino al lote:', 'bovinos al lote:']
    },


    target: {
        TittleTarget: 'Hoja de vida',
        TittleGrafic: 'Desempeño del bovino',
        TittleMenu: 'Opciones del bovino',
        TargetMenu: ['Reproducción', 'Sintomas', 'Pesaje', 'Producción', 'vender', 'Dar de baja']
    }
}

export default cattleModule