const generals = {
    AppName: 'Trazii',
    Profile: 'Mi perfil',
    Update: 'Actualizar',
    Farm: 'Finca',
    Specie: 'Bovinos',
    LogIn: 'Ingresa',
    SignIn: 'Registrate',
    LogOut: 'Cerrar sessión',
    Return: 'Volver',
    RecoverPassword: 'Recuperar contraseña',
    Email: 'Correo electrónico',
    User: 'Usuario',
    Password: 'Contraseña',
    DefinePassword: 'Defina su contraseña de acseso',
    Id: 'ID',
    Profile: 'Perfil',
    Exit: 'Salir',
    Edit: 'Editar',
    Save: 'Guardar',
    SelectOption: 'Seleccione una opción',
    SelectCattle: 'Seleccione el lote',
    SelectCow: 'Seleccione el bovino:',
    Options: 'Opciones',
    Cattle: 'Bovino',
    Sex: ['Hembra', 'Macho'],
    Register: 'Registrar',
    TenantRegistration: 'Registro de cuenta',
    DataSettings: 'Gestión de datos',
    MeasurementUnits: ['Miligramos(mg)', 'Gramos(g)', 'Kilogramos(kg)', 'Toneladas(ton)', 'Mililitros(ml)', 'Litros(l)', 'Centímetros cúbicos (cm3)'],
    Synchronization: 'Sincronización',
    SyncUp: 'Sincronizar',
    SynchronizationMessage: 'Seleccione la cantidad de semanas que desea mantener en el historico de la finca:',
    WelcomMessage: 'Bienvenidos a Trazii',
    ConfirmationMessage: '!Entendido, quiero registrarme!'
}

export default generals