const grasslandModule = {
    index: {
        Tittle: 'Mis potreros',
        Target: 'Hoja de vida de potrero',
        Grazing: 'Registro de pastoreo',
        Supplies: 'Aplicación de insumos',
        Input: 'Entrada a pastoreo',
        Output: 'Salida de pastoreo',
        Pass: 'Fertilización',
        Fumigation: 'Fumigación',
        Plow: 'Mecanización',
        Sow: 'Siembra',

    },
    form: {
        Id: 'Identificación del potrero',
        NewGrassland: 'Nuevo potrero',
        AddGrassland: 'Agregar potrero',
        TypeGrassland: 'Especie forrajera predominante',
        Area: 'Area del potrero (m2)',
        Events: 'Registrar eventos',
        GrazingMessage: '¡Esta apunto de registrar el siguiente inicio de pastoreo!',
        PassInformation: 'Información de la fertilización',
        PassType: ['Organico', 'Mineral', 'Sintético', 'Mixto'],
        PassLabels: ['Tipo de producto', 'Nombre del producto', 'Dosis aplicada', 'Unidadad de medida', 'Registrar fertilización'],
        FumigationInformation: 'Información de la fumigación',
        FumigationLabels: ['Registrar fumigación'],
        GrasslandsType: [
            { label: 'Alfalfa', value: 'Alfalfa' },
            { label: 'Angletón', value: 'Angletón' },
            { label: 'Avena forrajera', value: 'Avena forrajera' },
            { label: 'Azul orchoro', value: 'Azul orchoro' },
            { label: 'Bore', value: 'Bore' },
            { label: 'Botón de Oro', value: 'Botón de Oro' },
            { label: 'Brachiaria sp', value: 'Brachiaria sp' },
            { label: 'Brachiaria brizanta', value: 'Brachiaria brizanta' },
            { label: 'Brachiaria decumbens', value: 'Brachiaria decumbens' },
            { label: 'Brachiaria humidicola', value: 'Brachiaria humidicola' },
            { label: 'Brasilero', value: 'Brasilero' },
            { label: 'Brizantha', value: 'Brizantha' },
            { label: 'Canavalia', value: 'Canavalia' },
            { label: 'Caña forrajera', value: 'Caña forrajera' },
            { label: 'Carimagua', value: 'Carimagua' },
            { label: 'Centrosema', value: 'Centrosema' },
            { label: 'Climacuna', value: 'Climacuna' },
            { label: 'Colosuana', value: 'Colosuana' },
            { label: 'Cratylia', value: 'Cratylia' },
            { label: 'Cuba 22', value: 'Cuba 22' },
            { label: 'Desmodium sp', value: 'Desmodium sp' },
            { label: 'Elefante', value: 'Elefante' },
            { label: 'Estrella', value: 'Estrella' },
            { label: 'Falsa poa', value: 'Falsa poa' },
            { label: 'Festuca', value: 'Festuca' },
            { label: 'Grama', value: 'Grama' },
            { label: 'Gramalote', value: 'Gramalote' },
            { label: 'Guatemala', value: 'Guatemala' },
            { label: 'Guinea', value: 'Guinea' },
            { label: 'Imperial', value: 'Imperial' },
            { label: 'Kikuyo', value: 'Kikuyo' },
            { label: 'King grass', value: 'King grass' },
            { label: 'Maiz forrajero', value: 'Maiz forrajero' },
            { label: 'Mani forrajero', value: 'Mani forrajero' },
            { label: 'Maralfalta', value: 'Maralfalta' },
            { label: 'Micay', value: 'Micay' },
            { label: 'Morera', value: 'Morera' },
            { label: 'Mulato', value: 'Mulato' },
            { label: 'Panameño', value: 'Panameño' },
            { label: 'Pangola', value: 'Pangola' },
            { label: 'Pará', value: 'Pará' },
            { label: 'Rabano Forrajero', value: 'Rabano Forrajero' },
            { label: 'Remolacha forrajera', value: 'Remolacha forrajera' },
            { label: 'Ryegrass ', value: 'Ryegrass ' },
            { label: 'Sorgo forrajero', value: 'Sorgo forrajero' },
            { label: 'Soya', value: 'Soya' },
            { label: 'Taiwan', value: 'Taiwan' },
            { label: 'Treból', value: 'Treból' },
            { label: 'Trigo forrajero', value: 'Trigo forrajero' },
            { label: 'Yuca forrajera', value: 'Yuca forrajera' },
            { label: 'Otro', value: 'Otro' },

        ],
        PassType: [
            { label: 'Urea', value: 'Urea' },
            { label: 'DAP', value: 'DAP' },
            { label: 'Nutrán', value: 'Nutrán' },
            { label: 'Sulfato de amonio', value: 'Sulfato de amonio' },
            { label: 'Fosfato diamónico, DAP', value: 'Fosfato diamónico, DAP' },
            { label: 'Fosfato monoamónico, MAP', value: 'Fosfato monoamónico, MAP' },
            { label: 'Triple superfosfato', value: 'Triple superfosfato' },
            { label: 'Roca fosfórica', value: 'Roca fosfórica' },
            { label: '10-30-10', value: '10-30-10' },
            { label: '12-24-12', value: '12-24-12' },
            { label: 'Superfosfato sencillo', value: 'Superfosfato sencillo' },
            { label: 'Cloruro de potasio', value: 'Cloruro de potasio' },
            { label: 'Sulfato de potasio', value: 'Sulfato de potasio' },
            { label: 'Cal agrícola', value: 'Cal agrícola' },
            { label: 'Cal dolomita', value: 'Cal dolomita' },
            { label: 'Sulfato de magnesio', value: 'Sulfato de magnesio' },
            { label: 'Pollinaza', value: 'Pollinaza' },
            { label: 'Gallinaza', value: 'Gallinaza' },
            { label: 'Excretas de cerdos, fresca', value: 'Excretas de cerdos, fresca' },
            { label: 'Excretas de cabras, fresca', value: 'Excretas de cabras, fresca' },
            { label: 'Excretas de bovinos, fresca', value: 'Excretas de bovinos, fresca' },
            { label: 'Micronutrientes', value: 'Micronutrientes' },
            { label: 'Formulación especial', value: 'Formulación especial' },
            { label: 'Otro', value: 'Otro' },

        ],
        FumigationType: [
            { label: 'Glifosato', value: 'Glifosato' },
            { label: '2,4-D', value: '2,4-D' },
            { label: 'Picloram', value: 'Picloram' },
            { label: 'Triclopyr', value: 'Triclopyr' },
            { label: 'Paraquat', value: 'Paraquat' },
            { label: 'Atrazina', value: 'Atrazina' },
            { label: 'Metsulfurón metilo', value: 'Metsulfurón metilo' },
            { label: 'Clorpirifos', value: 'Clorpirifos' },
            { label: 'Fluazifop-P-butil', value: 'Fluazifop-P-butil' },
            { label: '2,4-DB', value: '2,4-DB' },
            { label: 'Metsulfurón-metilo + Aminopiralid', value: 'Metsulfurón-metilo + Aminopiralid' },
            { label: 'Dicamba', value: 'Dicamba' },
            { label: 'Cipermetrina', value: 'Cipermetrina' },
            { label: 'Ivermectina', value: 'Ivermectina' },
            { label: 'Deltametrina', value: 'Deltametrina' },
            { label: 'Diazinon', value: 'Diazinon' },
            { label: 'Abamectina', value: 'Abamectina' },
            { label: 'Permetrina', value: 'Permetrina' },
            { label: 'Organofosforados', value: 'Organofosforados' },
            { label: 'Cipermetrina', value: 'Cipermetrina' },
            { label: 'Cyromazina', value: 'Cyromazina' },
            { label: 'Doramectina', value: 'Doramectina' },
            { label: 'Amitraz', value: 'Amitraz' },
            { label: 'Fipronil', value: 'Fipronil' },
            { label: 'Otro', value: 'Otro' },

        ]

    }
}

export default grasslandModule