const healtModule = {
    index: {
        Tittle: 'Eventos de salud',
        Symptom: 'Síntomas',
        Treatment: 'Tratamientos',
        Medicines: 'Medicamentos',
        Discharge: 'Dar de alta',
        ConfigureTreatments: 'Configurar tratamientos',
        ConsultTreatment: 'Consulta de tratamientos existentes',
        Veterinary: 'Consultar veterinarios',
        Apply: 'Aplicar',
        CurrentTreatments: 'Tratamientos en curso',
        SelectTreataments: 'Desea registrar un tratamiento para',
        Procedure: 'Procedimiento veterinario'
    },
    form: {
        ReportName: 'Nombre de quien reporta',
        SymptomOptions: [
            { key: '1', value: 'Fiebre' },
            { key: '2', value: 'Grumos en leche' },
            { key: '3', value: 'Inflamación en cuarto' },
            { key: '4', value: 'Cojera' },
            { key: '5', value: 'Secreción' },
            { key: '6', value: 'Vómito' },
            { key: '7', value: 'Vaca caida' },
            { key: '8', value: 'Orina con sangre o amarillenta' },
            { key: '9', value: 'Diarrea' },
            { key: '10', value: 'Entamboramiento/timpanismo' },
            { key: '11', value: 'Tambaleo/mareo' },
            { key: '12', value: 'Ojos hundidos' },
            { key: '13', value: 'Inflamaciones en ojos' },
            { key: '14', value: 'Gusanera/acceso en piel' },
            { key: '15', value: 'Mucosas palidas, amarillas o secas' },
            { key: '16', value: 'Brotes en la piel' },
            { key: '16', value: 'Comportamientos extraños' },
            { key: '16', value: 'brahamidos intensos y frecuentes' },

        ],
        SyptomSelect: 'Seleccione los síntomas observados',
        SyptomLabel: 'Síntomas',
        SyptomPlaceHolder: '  Describa con mayor detalle si es necesario',
        SyptomSave: 'Registrar síntomas',
        InitTreatment: 'Iniciar tratamiento',
        ConfigureTreatments: 'Configuración de tratamientos',
        TreatmentName: 'Nombre del tratamiento',
        InitTreatment: 'Iniciar tratamiento',
        DiseaseName: 'Nombre de la enfermedad',
        DiseaseOptions: [
            { 'key': '1', 'value': 'Anaplasmosis' },
            { 'key': '2', 'value': 'Babesiosis' },
            { 'key': '3', 'value': 'Brucelosis' },
            { 'key': '4', 'value': 'Carbon sintomatico' },
            { 'key': '5', 'value': 'Clostridiosis' },
            { 'key': '6', 'value': 'Diarrea viral bovina' },
            { 'key': '7', 'value': 'Endometritis' },
            { 'key': '8', 'value': 'Estomatitis vesicular (EV)' },
            { 'key': '9', 'value': 'Fiebre aftosa' },
            { 'key': '10', 'value': 'Fiebre de leche' },
            { 'key': '11', 'value': 'Hematuria' },
            { 'key': '12', 'value': 'Infección' },
            { 'key': '13', 'value': 'Leptospirosis' },
            { 'key': '14', 'value': 'Leucosis bovina' },
            { 'key': '15', 'value': 'Mastitis' },
            { 'key': '16', 'value': 'Neumonia Bovina' },
            { 'key': '17', 'value': 'Parasitos externos' },
            { 'key': '18', 'value': 'Parasitos internos' },
            { 'key': '19', 'value': 'Problema de pesuña' },
            { 'key': '20', 'value': 'Timpanismo' },
            { 'key': '21', 'value': 'Tripanomiasis' },
            { 'key': '22', 'value': 'Tuberculosis' },
            { 'key': '23', 'value': 'Tuberculosis bovina' },
            { 'key': '24', 'value': 'Vaca caida' }
        ],
        Medicine: 'Medicamento',
        MedicineOptions: [
            { label: 'Abamectin', value: 'Abamectin' },
            { label: 'Acetato de melengestrol', value: 'Acetato de melengestrol' },
            { label: 'Acetato de trembolona', value: 'Acetato de trembolona' },
            { label: 'Amoxicillina', value: 'Amoxicillina' },
            { label: 'Albenil L.A.', value: 'Albenil L.A.' },
            { label: 'Baytril', value: 'Baytril' },
            { label: 'Bencilpenicilina/Bencilpenicilina procaínica', value: 'Bencilpenicilina/Bencilpenicilina procaínica' },
            { label: 'Biomectin Gold', value: 'Biomectin Gold' },
            { label: 'Bio-Cox', value: 'Bio-Cox' },
            { label: 'Ceptiofur', value: 'Ceptiofur' },
            { label: 'Ciflutrín', value: 'Ciflutrín' },
            { label: 'Cihalotrin', value: 'Cihalotrin' },
            { label: 'Cipermetrina y alpfa-cypermetrina', value: 'Cipermetrina y alpfa-cypermetrina' },
            { label: 'Clenbuterol', value: 'Clenbuterol' },
            { label: 'Clortetraciclina/Oxitetraciclina/Tetraciclina', value: 'Clortetraciclina/Oxitetraciclina/Tetraciclina' },
            { label: 'Closantel', value: 'Closantel' },
            { label: 'Closantel Plus', value: 'Closantel Plus' },
            { label: 'Cloxacilina + Ampicilina', value: 'Cloxacilina + Ampicilina' },
            { label: 'Colistin', value: 'Colistin' },
            { label: 'Danofloxacina', value: 'Danofloxacina' },
            { label: 'Dectomax', value: 'Dectomax' },
            { label: 'Deltametrin', value: 'Deltametrin' },
            { label: 'Dexametasona', value: 'Dexametasona' },
            { label: 'Dihidroestreptomicina/Estreptomicina', value: 'Dihidroestreptomicina/Estreptomicina' },
            { label: 'Diminazina', value: 'Diminazina' },
            { label: 'Doramectin', value: 'Doramectin' },
            { label: 'Draxxin', value: 'Draxxin' },
            { label: 'Eprinex', value: 'Eprinex' },
            { label: 'Eprinomectín', value: 'Eprinomectín' },
            { label: 'Espectinomicina', value: 'Espectinomicina' },
            { label: 'Espiramicina', value: 'Espiramicina' },
            { label: 'Estradiol-17beta', value: 'Estradiol-17beta' },
            { label: 'Febantel/Fenbendazol/Oxfendazol', value: 'Febantel/Fenbendazol/Oxfendazol' },
            { label: 'Finaplix', value: 'Finaplix' },
            { label: 'Florfenicol Gold', value: 'Florfenicol Gold' },
            { label: 'Fluazuron', value: 'Fluazuron' },
            { label: 'Flumequina', value: 'Flumequina' },
            { label: 'Gentamicina', value: 'Gentamicina' },
            { label: 'Imidocarb', value: 'Imidocarb' },
            { label: 'Ivermectina', value: 'Ivermectina' },
            { label: 'Ivomec', value: 'Ivomec' },
            { label: 'Levamisol', value: 'Levamisol' },
            { label: 'Lincospectin', value: 'Lincospectin' },
            { label: 'Lincomicina', value: 'Lincomicina' },
            { label: 'Maduramicina', value: 'Maduramicina' },
            { label: 'Maxidex', value: 'Maxidex' },
            { label: 'Metoclopramida Gold', value: 'Metoclopramida Gold' },
            { label: 'Monensina', value: 'Monensina' },
            { label: 'Monepantel', value: 'Monepantel' },
            { label: 'Moxidectin', value: 'Moxidectin' },
            { label: 'Neomicina', value: 'Neomicina' },
            { label: 'Neomicina + Bacitracina', value: 'Neomicina + Bacitracina' },
            { label: 'Noromectin', value: 'Noromectin' },
            { label: 'Noromectin Plus', value: 'Noromectin Plus' },
            { label: 'Nuflor', value: 'Nuflor' },
            { label: 'Oxitetraciclina', value: 'Oxitetraciclina' },
            { label: 'Oxytetracycline + Neomycin', value: 'Oxytetracycline + Neomycin' },
            { label: 'Oxytetracycline Gold', value: 'Oxytetracycline Gold' },
            { label: 'Pirlimycina', value: 'Pirlimycina' },
            { label: 'Progesterona', value: 'Progesterona' },
            { label: 'Ractopamine hydrochloride', value: 'Ractopamine hydrochloride' },
            { label: 'Revalor', value: 'Revalor' },
            { label: 'Ripercol', value: 'Ripercol' },
            { label: 'Rumensin', value: 'Rumensin' },
            { label: 'Sulfadimidina', value: 'Sulfadimidina' },
            { label: 'Testosterona', value: 'Testosterona' },
            { label: 'Tilan', value: 'Tilan' },
            { label: 'Tildipirosina Gold', value: 'Tildipirosina Gold' },
            { label: 'Tilosina', value: 'Tilosina' },
            { label: 'Triclabendazol', value: 'Triclabendazol' },
            { label: 'Triclorfon (metrifonato)', value: 'Triclorfon (metrifonato)' },
            { label: 'Tulan', value: 'Tulan' },
            { label: 'Tylan', value: 'Tylan' },
            { label: 'Tulatromicina Gold', value: 'Tulatromicina Gold' },
            { label: 'Vetegard Gold', value: 'Vetegard Gold' },
            { label: 'Zeranol', value: 'Zeranol' },
            { label: 'Ractopamine hydrochloride', value: 'Ractopamine hydrochloride' }
        ],
        Dose: 'Dosis por kilogramo de peso vivo',
        Measurement: 'Unidad',
        MeasurementOptions: [
            { key: '1', value: 'Litros' },
            { key: '1', value: 'Centímetros cubicos' },
            { key: '1', value: 'Mililitros' },
            { key: '1', value: 'Kilogramos' },
            { key: '1', value: 'Gramos' },
            { key: '1', value: 'Miligramos' },
            { key: '1', value: 'Microgramos' },
        ],
        Applications: 'Número de aplicaciones',
        Frecuency: 'Frecuencia de aplicación',
        HelpFrecuency: ['Cada', 'Horas'],
        AdministrationType: 'Tipo de administración',
        AdministrationMode: [
            { key: '1', value: 'Intra venosa' },
            { key: '2', value: 'Intra muscular' },
            { key: '3', value: 'Intra mamario' },
            { key: '4', value: 'Subcutanea' },
            { key: '5', value: 'Oral' },
            { key: '6', value: 'Tópica' },
            { key: '7', value: 'Optálmica' }
        ],
        Withdrawal: 'Días de retiro',
        TreatmentSave: 'Registrar tratamiento',
        NewTreatment: 'Iniciar nuevo tratamiento',
        NewConfigTreatment: 'Configurar tratamiento',
        TreatmentHeadertable: ['NOMBRE', 'MEDICAMENTO', 'DOSIS', 'SEGUIMIENTO', 'APLICAR'],
        currentTreatment: 'Tratamiento en proceso',
        TreatmentModalTitles: ['Enfermedad asociada', 'Tipo de aplicación', 'Cantidad de aplicaciones', 'Observaciones'],
        AplicationButtom: 'Aplicar la dosis Nro.',
        ProceduresLabel: 'Tipo de procedimiento',
        ProceduresType: [
            { key: 1, value: 'Castración' },
            { key: 2, value: 'Cirugía' },
            { key: 3, value: 'Podología' },
            { key: 4, value: 'Topización' },
            { key: 5, value: 'Otro'}]

    },
}

export default healtModule